/*
 * This source file was generated by the Gradle 'init' task
 */
package org.sarahyoo.bmi;

import java.awt.Color;
import java.awt.Dimension;

import javax.swing.JFrame;

public class App extends JFrame {

    public App () {
        setTitle("BMI Calculator");
        setPreferredSize(new Dimension(400, 300));
        setForeground(Color.black);
        pack();
        add(new BMI(this));
        setVisible(true);
    }

    public static void main(String[] args) {
        new App();
    }
}
