/*
 * This source file was generated by the Gradle 'init' task
 */
package org.sarahyoo.bmi;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void check_project_build() {
    }
}
